name: Sync Articles

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci || npm install

    - name: Run article sync
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        echo "Starting article sync at $(date)"
        npm run sync
        echo "Sync completed at $(date)"

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: sync-logs
        path: "*.log"
        retention-days: 7

    - name: Notify on failure (optional)
      if: failure()
      run: |
        echo "Article sync failed. Check the logs for details."
        # You can add notification logic here (e.g., send email, Slack message, etc.)

    - name: Report sync metrics
      if: always()
      run: |
        echo "Sync job completed with status: ${{ job.status }}"
        # You can send metrics to monitoring services here
